
import java.sql.*;
import java.util.Vector;
import javax.swing.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Etaireia_Edit extends javax.swing.JFrame {
     String DB_URL = SQL_GUI.DB_URL ;
    String username = SQL_GUI.USERNAME;
    String password = SQL_GUI.PASSWORD;
    private int deleteItem;
    
     
     
    public Etaireia_Edit() {
        initComponents();
        UpdateDB();
        setLocationRelativeTo(null);
    }
    
    public  void UpdateDB() {
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection(DB_URL,username,password);
            
            PreparedStatement stmnt = con.prepareStatement("SELECT * FROM etaireia");
            
            ResultSet resultSet = stmnt.executeQuery();
            
            ResultSetMetaData metadata = resultSet.getMetaData();
            int numberOfColumns = metadata.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)Etaireia_Table.getModel();
                    RecordTable.setRowCount(0);
                    
             while (resultSet.next()){
                 
             Vector columnData = new Vector();
                for (int i = 1; i <= numberOfColumns; i++){
                    columnData.add(resultSet.getLong("AFM"));
                    columnData.add(resultSet.getString("DOY"));
                    columnData.add(resultSet.getString("name"));
                    columnData.add(resultSet.getLong("tel"));
                    columnData.add(resultSet.getString("street"));
                    columnData.add(resultSet.getInt("num"));
                    columnData.add(resultSet.getString("city"));
                    columnData.add(resultSet.getString("country"));
                }                 
                RecordTable.addRow(columnData);
             }
       
        }catch (Exception ex) {
             JOptionPane.showMessageDialog(null, ex);
        }
     } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEtaireia_AFM = new javax.swing.JTextField();
        txtEtaireia_DOY = new javax.swing.JTextField();
        txtEtaireia_Name = new javax.swing.JTextField();
        txtEtaireia_Telephone = new javax.swing.JTextField();
        txtEtaireia_Street = new javax.swing.JTextField();
        txtEtaireia_Num = new javax.swing.JTextField();
        txtEtaireia_City = new javax.swing.JTextField();
        txtEtaireia_Country = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Etaireia_Table = new javax.swing.JTable();
        btnEtaireia_Delete = new javax.swing.JButton();
        btnEtaireia_back = new javax.swing.JButton();
        btnEtaireia_Update = new javax.swing.JButton();
        btnEtaireia_Insert = new javax.swing.JButton();
        btnEtaireia_Reset = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("AFM :");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("DOY :");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Name :");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Telephone :");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Street :");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Num :");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("City :");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Country :");

        txtEtaireia_AFM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtEtaireia_AFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEtaireia_AFMActionPerformed(evt);
            }
        });

        txtEtaireia_DOY.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtEtaireia_Name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtEtaireia_Telephone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtEtaireia_Street.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtEtaireia_Num.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtEtaireia_City.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtEtaireia_Country.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Etaireia");

        Etaireia_Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Etaireia_Table.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        Etaireia_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AFM", "DOY", "Name", "Telephone", "Street", "Num", "City", "Country"
            }
        ));
        Etaireia_Table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Etaireia_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Etaireia_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Etaireia_Table);

        btnEtaireia_Delete.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_Delete.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_Delete.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_Delete.setText("Delete");
        btnEtaireia_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_DeleteActionPerformed(evt);
            }
        });

        btnEtaireia_back.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_back.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_back.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_back.setText("← Back");
        btnEtaireia_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_backActionPerformed(evt);
            }
        });

        btnEtaireia_Update.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_Update.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_Update.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_Update.setText("Update");
        btnEtaireia_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_UpdateActionPerformed(evt);
            }
        });

        btnEtaireia_Insert.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_Insert.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_Insert.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_Insert.setText("Insert");
        btnEtaireia_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_InsertActionPerformed(evt);
            }
        });

        btnEtaireia_Reset.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_Reset.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_Reset.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_Reset.setText("Reset");
        btnEtaireia_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEtaireia_AFM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEtaireia_DOY, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEtaireia_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEtaireia_Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEtaireia_Street, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEtaireia_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEtaireia_City, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEtaireia_Country, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnEtaireia_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnEtaireia_Insert)
                .addGap(8, 8, 8)
                .addComponent(btnEtaireia_Update)
                .addGap(5, 5, 5)
                .addComponent(btnEtaireia_Delete)
                .addGap(488, 488, 488)
                .addComponent(btnEtaireia_back))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEtaireia_AFM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEtaireia_DOY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEtaireia_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEtaireia_Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEtaireia_Street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEtaireia_Num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txtEtaireia_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEtaireia_Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnEtaireia_Reset)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEtaireia_Insert)
                    .addComponent(btnEtaireia_Update)
                    .addComponent(btnEtaireia_Delete)
                    .addComponent(btnEtaireia_back)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEtaireia_AFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEtaireia_AFMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEtaireia_AFMActionPerformed

    private void btnEtaireia_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_UpdateActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            
            PreparedStatement stmnt = con.prepareStatement("UPDATE etaireia SET  DOY = ?, name = ?, tel = ?, street = ?, num = ?,city = ?,country = ? WHERE AFM = ?");
                        
            stmnt.setString(1,txtEtaireia_DOY.getText());
            stmnt.setString(2,txtEtaireia_Name.getText());
            stmnt.setString(3,txtEtaireia_Telephone.getText());
            stmnt.setString(4,txtEtaireia_Street.getText());
            stmnt.setString(5,txtEtaireia_Num.getText());
            stmnt.setString(6,txtEtaireia_City.getText());
            stmnt.setString(7,txtEtaireia_Country.getText());
            stmnt.setString(8,txtEtaireia_AFM.getText());
            
            stmnt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Record Updated");
            UpdateDB();            
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Etaireia_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(Etaireia_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }
    }//GEN-LAST:event_btnEtaireia_UpdateActionPerformed

    private void btnEtaireia_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_InsertActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            
            PreparedStatement stmnt = con.prepareStatement("INSERT INTO etaireia(AFM,DOY,name,tel,street,num,city,country)value(?,?,?,?,?,?,?,?)");
            
            stmnt.setString(1,txtEtaireia_AFM.getText());
            stmnt.setString(2,txtEtaireia_DOY.getText());
            stmnt.setString(3,txtEtaireia_Name.getText());
            stmnt.setString(4,txtEtaireia_Telephone.getText());
            stmnt.setString(5,txtEtaireia_Street.getText());
            stmnt.setString(6,txtEtaireia_Num.getText());
            stmnt.setString(7,txtEtaireia_City.getText());
            stmnt.setString(8,txtEtaireia_Country.getText());
            
            stmnt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            UpdateDB();            
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Etaireia_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(null,"Etaireia entry already exists");
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(Etaireia_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }
    }//GEN-LAST:event_btnEtaireia_InsertActionPerformed

    private void btnEtaireia_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_ResetActionPerformed
        txtEtaireia_AFM.setText("");
        txtEtaireia_DOY.setText("");
        txtEtaireia_Name.setText("");
        txtEtaireia_Telephone.setText("");
        txtEtaireia_Street.setText("");
        txtEtaireia_Num.setText("");
        txtEtaireia_City.setText("");
        txtEtaireia_Country.setText("");
        
        txtEtaireia_AFM.enable();
    }//GEN-LAST:event_btnEtaireia_ResetActionPerformed

    private void Etaireia_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Etaireia_TableMouseClicked
       DefaultTableModel RecordTable = (DefaultTableModel)Etaireia_Table.getModel();
       int SelectedRows = Etaireia_Table.getSelectedRow();
       
       txtEtaireia_AFM.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
       txtEtaireia_DOY.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
       txtEtaireia_Name.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
       txtEtaireia_Telephone.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
       txtEtaireia_Street.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
       txtEtaireia_Num.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
       txtEtaireia_City.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
       txtEtaireia_Country.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
       
       txtEtaireia_AFM.disable();
    }//GEN-LAST:event_Etaireia_TableMouseClicked

    private void btnEtaireia_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_DeleteActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)Etaireia_Table.getModel();
        int SelectedRows = Etaireia_Table.getSelectedRow();
        
        try{
            
            int AFM;
            AFM = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            
             deleteItem = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this entry ?","Warning!",JOptionPane.YES_NO_OPTION);
            if (deleteItem == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.jdbc.Driver");
               Connection con = DriverManager.getConnection(DB_URL,username,password);
                PreparedStatement stmnt = con.prepareStatement("DELETE FROM etaireia WHERE AFM = ?");
                
                stmnt.setLong(1, AFM);
                stmnt.executeUpdate();
                JOptionPane.showMessageDialog(this,"Entry Deleted");
                UpdateDB();
                
                txtEtaireia_AFM.setText("");
                txtEtaireia_AFM.requestFocus();
                txtEtaireia_DOY.setText("");
                txtEtaireia_Name.setText("");
                txtEtaireia_Telephone.setText("");
                txtEtaireia_Street.setText("");
                txtEtaireia_Num.setText("");
                txtEtaireia_City.setText("");
                txtEtaireia_Country.setText("");
            }
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Etaireia_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLException ex){
            System.err.println(ex);
        }
    }//GEN-LAST:event_btnEtaireia_DeleteActionPerformed

    private void btnEtaireia_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_backActionPerformed
        this.setVisible(false);
        new Table_Select().toFront();
         new Table_Select().setVisible(true);
        new Table_Select().setState(java.awt.Frame.NORMAL);
       
    }//GEN-LAST:event_btnEtaireia_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Etaireia_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Etaireia_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Etaireia_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Etaireia_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etaireia_Edit().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Etaireia_Table;
    private javax.swing.JButton btnEtaireia_Delete;
    private javax.swing.JButton btnEtaireia_Insert;
    private javax.swing.JButton btnEtaireia_Reset;
    private javax.swing.JButton btnEtaireia_Update;
    private javax.swing.JButton btnEtaireia_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEtaireia_AFM;
    private javax.swing.JTextField txtEtaireia_City;
    private javax.swing.JTextField txtEtaireia_Country;
    private javax.swing.JTextField txtEtaireia_DOY;
    private javax.swing.JTextField txtEtaireia_Name;
    private javax.swing.JTextField txtEtaireia_Num;
    private javax.swing.JTextField txtEtaireia_Street;
    private javax.swing.JTextField txtEtaireia_Telephone;
    // End of variables declaration//GEN-END:variables
}
