
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Has_Degree_Edit extends javax.swing.JFrame {
    String DB_URL = SQL_GUI.DB_URL ;
   String username = SQL_GUI.USERNAME;
   String password = SQL_GUI.PASSWORD;
    private int deleteItem;
    /**
     * Creates new form Has_Degree_Edit
     */
    public Has_Degree_Edit() {
        initComponents();
        UpdateDB();
        UpdateCombo_title();
        UpdateCombo_idryma();
        UpdateCombo_employee();
        txtHDeg_etos.setYear(2024);
        setLocationRelativeTo(null);
    }
    
    public  void UpdateDB() {
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            
            PreparedStatement stmnt = con.prepareStatement("SELECT * FROM has_degree");
            
            ResultSet resultSet = stmnt.executeQuery();
            
            ResultSetMetaData metadata = resultSet.getMetaData();
            int numberOfColumns = metadata.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)Has_Degree_Table.getModel();
                    RecordTable.setRowCount(0);
                    
             while (resultSet.next()){
                 
             Vector columnData = new Vector();
                for (int i = 1; i <= numberOfColumns; i++){
                    columnData.add(resultSet.getString("degr_title"));
                    columnData.add(resultSet.getString("degr_idryma"));
                    columnData.add(resultSet.getString("cand_usrname"));
                    columnData.add(resultSet.getInt("etos"));
                    columnData.add(resultSet.getFloat("grade"));
                    
                    
                    
                }                 
                RecordTable.addRow(columnData);
             }
       
        }catch (Exception ex) {
             JOptionPane.showMessageDialog(null, ex);
        }
     } 
    
    public void UpdateCombo_title(){
        String dropdown = "Select * from degree";
        try{
            Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection(DB_URL,username,password);
            PreparedStatement stmnt = con.prepareStatement(dropdown);
            ResultSet rs = stmnt.executeQuery();
            
            while(rs.next()){
                txtHDeg_titlos.addItem(rs.getString("titlos"));
            }
            
        }catch (Exception e){
            
        }
        
    }

    public void UpdateCombo_idryma(){
        String dropdown = "Select * from degree";
        try{
            Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection(DB_URL,username,password);
            PreparedStatement stmnt = con.prepareStatement(dropdown);
            ResultSet rs = stmnt.executeQuery();
            
            while(rs.next()){
                txtHDeg_idryma.addItem(rs.getString("idryma"));
            }
            
        }catch (Exception e){
            
        }
        
    }
    
    public void UpdateCombo_employee(){
        String dropdown = "Select * from employee";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            PreparedStatement stmnt = con.prepareStatement(dropdown);
            ResultSet rs = stmnt.executeQuery();
            
            while(rs.next()){
                txtHDeg_employee.addItem(rs.getString("username"));
            }
            
        }catch (Exception e){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEtaireia_Delete = new javax.swing.JButton();
        txtHDeg_grade = new javax.swing.JTextField();
        btnEtaireia_back = new javax.swing.JButton();
        txtHDeg_titlos = new javax.swing.JComboBox<>();
        btnEtaireia_Update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEtaireia_Insert = new javax.swing.JButton();
        btnEtaireia_Reset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Has_Degree_Table = new javax.swing.JTable();
        txtHDeg_idryma = new javax.swing.JComboBox<>();
        txtHDeg_employee = new javax.swing.JComboBox<>();
        txtHDeg_etos = new com.toedter.calendar.JYearChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        btnEtaireia_Delete.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_Delete.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_Delete.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_Delete.setText("Delete");
        btnEtaireia_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_DeleteActionPerformed(evt);
            }
        });

        txtHDeg_grade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnEtaireia_back.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_back.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_back.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_back.setText("← Back");
        btnEtaireia_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_backActionPerformed(evt);
            }
        });

        txtHDeg_titlos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        txtHDeg_titlos.setSelectedIndex(-1);

        btnEtaireia_Update.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_Update.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_Update.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_Update.setText("Update");
        btnEtaireia_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_UpdateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Degree Tiltle :");

        btnEtaireia_Insert.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_Insert.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_Insert.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_Insert.setText("Insert");
        btnEtaireia_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_InsertActionPerformed(evt);
            }
        });

        btnEtaireia_Reset.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_Reset.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_Reset.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_Reset.setText("Reset");
        btnEtaireia_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_ResetActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Has Degree");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Degree Uni. :");

        Has_Degree_Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Has_Degree_Table.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        Has_Degree_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Degree Title", "Degree Uni.", "Employee", "Year", "Grade"
            }
        ));
        Has_Degree_Table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Has_Degree_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Has_Degree_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Has_Degree_Table);

        txtHDeg_idryma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        txtHDeg_idryma.setSelectedIndex(-1);

        txtHDeg_employee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        txtHDeg_employee.setSelectedIndex(-1);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Employee :");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Year :");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Grade :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(695, 695, 695))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEtaireia_Insert)
                                .addGap(8, 8, 8)
                                .addComponent(btnEtaireia_Update)
                                .addGap(5, 5, 5)
                                .addComponent(btnEtaireia_Delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEtaireia_back)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel1)))
                                .addGap(18, 51, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHDeg_etos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHDeg_employee, javax.swing.GroupLayout.Alignment.TRAILING, 0, 138, Short.MAX_VALUE)
                                    .addComponent(txtHDeg_idryma, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHDeg_titlos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHDeg_grade))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnEtaireia_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtHDeg_titlos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHDeg_idryma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHDeg_employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHDeg_etos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHDeg_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnEtaireia_Reset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEtaireia_Insert)
                    .addComponent(btnEtaireia_Update)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEtaireia_Delete)
                        .addComponent(btnEtaireia_back)))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEtaireia_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_DeleteActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)Has_Degree_Table.getModel();
        int SelectedRows = Has_Degree_Table.getSelectedRow();

        try{
            
            

            deleteItem = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this entry ?","Warning!",JOptionPane.YES_NO_OPTION);
            if (deleteItem == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection(DB_URL,username,password);
                PreparedStatement stmnt = con.prepareStatement("DELETE FROM has_degree WHERE degr_title = ? and degr_idryma = ? and cand_usrname = ?");

                stmnt.setString(1,RecordTable.getValueAt(SelectedRows, 0).toString());
                stmnt.setString(2,RecordTable.getValueAt(SelectedRows, 1).toString());
                stmnt.setString(3,RecordTable.getValueAt(SelectedRows, 2).toString());
                stmnt.executeUpdate();
                JOptionPane.showMessageDialog(this,"Entry Deleted");
                UpdateDB();

                txtHDeg_titlos.setSelectedItem(null);
                txtHDeg_idryma.setSelectedItem(null);
                txtHDeg_employee.setSelectedItem(null);
                txtHDeg_etos.setYear(2024);
                txtHDeg_grade.setText("");

            }
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Project_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLException ex){
            System.err.println(ex);
        }
    }//GEN-LAST:event_btnEtaireia_DeleteActionPerformed

    private void btnEtaireia_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_backActionPerformed
        this.setVisible(false);
        new Table_Select().toFront();
        new Table_Select().setVisible(true);
        new Table_Select().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_btnEtaireia_backActionPerformed

    private void btnEtaireia_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_UpdateActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            PreparedStatement stmnt = con.prepareStatement("UPDATE has_degree SET  etos = ?, grade = ? WHERE degr_title = ? and degr_idryma = ? and cand_usrname = ?");

            stmnt.setInt(1,txtHDeg_etos.getYear());
            stmnt.setFloat(2,Float.parseFloat(txtHDeg_grade.getText()));
            stmnt.setString(3,(String)txtHDeg_titlos.getSelectedItem());
            stmnt.setString(4,(String)txtHDeg_idryma.getSelectedItem());
            stmnt.setString(5,(String)txtHDeg_employee.getSelectedItem());
            stmnt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Record Updated");
            UpdateDB();
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Project_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(Project_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        } 
    }//GEN-LAST:event_btnEtaireia_UpdateActionPerformed

    private void btnEtaireia_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_InsertActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            PreparedStatement stmnt = con.prepareStatement("INSERT INTO has_degree(degr_title,degr_idryma,cand_usrname,etos,grade)value(?,?,?,?,?)");
            
            stmnt.setString(1,(String)txtHDeg_titlos.getSelectedItem());
            stmnt.setString(2,(String)txtHDeg_idryma.getSelectedItem());
            stmnt.setString(3,(String)txtHDeg_employee.getSelectedItem());
            stmnt.setInt(4,txtHDeg_etos.getYear());
            stmnt.setFloat(5,Float.parseFloat(txtHDeg_grade.getText()));
            

            stmnt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            UpdateDB();
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Project_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(null,"Has_Degree entry already exists");
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(Project_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }
    }//GEN-LAST:event_btnEtaireia_InsertActionPerformed

    private void btnEtaireia_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_ResetActionPerformed
        txtHDeg_titlos.setSelectedItem(null);
        txtHDeg_idryma.setSelectedItem(null);
        txtHDeg_employee.setSelectedItem(null);
        txtHDeg_etos.setYear(2024);
        txtHDeg_grade.setText("");
        
        txtHDeg_titlos.enable();
        txtHDeg_idryma.enable();
        txtHDeg_employee.enable();
        

    }//GEN-LAST:event_btnEtaireia_ResetActionPerformed

    private void Has_Degree_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Has_Degree_TableMouseClicked
        txtHDeg_titlos.disable();
        txtHDeg_idryma.disable();
        txtHDeg_employee.disable();
        
        DefaultTableModel RecordTable = (DefaultTableModel)Has_Degree_Table.getModel();
        int SelectedRows = Has_Degree_Table.getSelectedRow();

        txtHDeg_titlos.setSelectedItem(RecordTable.getValueAt(SelectedRows, 0).toString());
        txtHDeg_idryma.setSelectedItem(RecordTable.getValueAt(SelectedRows, 1).toString());
        txtHDeg_employee.setSelectedItem(RecordTable.getValueAt(SelectedRows, 2).toString());
        txtHDeg_etos.setYear(Integer.parseInt(RecordTable.getValueAt(SelectedRows, 3).toString()));
        txtHDeg_grade.setText(RecordTable.getValueAt(SelectedRows, 4).toString());

    }//GEN-LAST:event_Has_Degree_TableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Has_Degree_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Has_Degree_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Has_Degree_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Has_Degree_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Has_Degree_Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Has_Degree_Table;
    private javax.swing.JButton btnEtaireia_Delete;
    private javax.swing.JButton btnEtaireia_Insert;
    private javax.swing.JButton btnEtaireia_Reset;
    private javax.swing.JButton btnEtaireia_Update;
    private javax.swing.JButton btnEtaireia_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> txtHDeg_employee;
    private com.toedter.calendar.JYearChooser txtHDeg_etos;
    private javax.swing.JTextField txtHDeg_grade;
    private javax.swing.JComboBox<String> txtHDeg_idryma;
    private javax.swing.JComboBox<String> txtHDeg_titlos;
    // End of variables declaration//GEN-END:variables
}
