
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */


public class HistoryApplies extends javax.swing.JFrame {
    String DB_URL = SQL_GUI.DB_URL ;
   String username = SQL_GUI.USERNAME;
   String password = SQL_GUI.PASSWORD;
    private int deleteItem;
    /**
     * Creates new form HistoryApplies
     */
    public HistoryApplies() {
        initComponents();
        UpdateDB();
        UpdateCombo_eval();
        setLocationRelativeTo(null);
    }
    
    public  void UpdateDB() {
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            
            PreparedStatement stmnt = con.prepareStatement("SELECT * FROM history_applies");
            
            ResultSet resultSet = stmnt.executeQuery();
            
            ResultSetMetaData metadata = resultSet.getMetaData();
            int numberOfColumns = metadata.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)HApplies_Table.getModel();
                    RecordTable.setRowCount(0);
                    
             while (resultSet.next()){
                 
             Vector columnData = new Vector();
                for (int i = 1; i <= numberOfColumns; i++){
                    columnData.add(resultSet.getString("employee"));
                    columnData.add(resultSet.getString("job"));                    
                    columnData.add(resultSet.getString("evaluator1"));
                    columnData.add(resultSet.getString("evaluator2"));
                    columnData.add(resultSet.getString("status"));                    
                    columnData.add(resultSet.getString("average"));
                    
                    
                    
                }                 
                RecordTable.addRow(columnData);
             }
       
        }catch (Exception ex) {
             JOptionPane.showMessageDialog(null, ex);
        }
     } 
    
    public void UpdateCombo_eval(){
        String dropdown = "Select * from evaluator";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            PreparedStatement stmnt = con.prepareStatement(dropdown);
            ResultSet rs = stmnt.executeQuery();
            
            while(rs.next()){
                combo_eval.addItem(rs.getString("username"));
            }
            
        }catch (Exception e){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eval_Dialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        eval_table = new javax.swing.JTable();
        DialogBack_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        eval_name = new javax.swing.JLabel();
        grade_dialog = new javax.swing.JDialog();
        DialogBack_btn2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        grade_table = new javax.swing.JTable();
        startgrade_txt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        endgrade_txt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HApplies_Table = new javax.swing.JTable();
        btnUser_Delete = new javax.swing.JButton();
        btnUser_back = new javax.swing.JButton();
        eval_procedure = new javax.swing.JButton();
        graderange_procedure = new javax.swing.JButton();
        combo_eval = new javax.swing.JComboBox<>();
        gradestart = new javax.swing.JComboBox<>();
        gradeend = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        eval_Dialog.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        eval_Dialog.setSize(new java.awt.Dimension(400, 650));

        eval_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eval_table.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        eval_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee", "Job ID"
            }
        ));
        eval_table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        eval_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eval_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(eval_table);

        DialogBack_btn.setBackground(new java.awt.Color(102, 102, 102));
        DialogBack_btn.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        DialogBack_btn.setForeground(new java.awt.Color(255, 255, 255));
        DialogBack_btn.setText("← Back");
        DialogBack_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DialogBack_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setText("Evaluator username :");

        eval_name.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout eval_DialogLayout = new javax.swing.GroupLayout(eval_Dialog.getContentPane());
        eval_Dialog.getContentPane().setLayout(eval_DialogLayout);
        eval_DialogLayout.setHorizontalGroup(
            eval_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eval_DialogLayout.createSequentialGroup()
                .addGroup(eval_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eval_DialogLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(DialogBack_btn))
                    .addGroup(eval_DialogLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eval_name))
                    .addGroup(eval_DialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        eval_DialogLayout.setVerticalGroup(
            eval_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eval_DialogLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(eval_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eval_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DialogBack_btn)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        grade_dialog.setSize(new java.awt.Dimension(400, 650));

        DialogBack_btn2.setBackground(new java.awt.Color(102, 102, 102));
        DialogBack_btn2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        DialogBack_btn2.setForeground(new java.awt.Color(255, 255, 255));
        DialogBack_btn2.setText("← Back");
        DialogBack_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DialogBack_btn2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setText("Grade range :");

        grade_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        grade_table.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        grade_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee", "Job ID"
            }
        ));
        grade_table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        grade_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grade_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(grade_table);

        startgrade_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setText("to");

        endgrade_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout grade_dialogLayout = new javax.swing.GroupLayout(grade_dialog.getContentPane());
        grade_dialog.getContentPane().setLayout(grade_dialogLayout);
        grade_dialogLayout.setHorizontalGroup(
            grade_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grade_dialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(grade_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DialogBack_btn2))
                .addGap(21, 21, 21))
            .addGroup(grade_dialogLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(startgrade_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endgrade_txt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        grade_dialogLayout.setVerticalGroup(
            grade_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grade_dialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(grade_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(startgrade_txt)
                    .addComponent(jLabel5)
                    .addComponent(endgrade_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DialogBack_btn2)
                .addGap(36, 36, 36))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("History_Applies");

        HApplies_Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        HApplies_Table.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        HApplies_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee", "Job ID", "Evaluator No1", "Evaluator No2", "Average", "Apply Status"
            }
        ));
        HApplies_Table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        HApplies_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HApplies_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(HApplies_Table);

        btnUser_Delete.setBackground(new java.awt.Color(102, 102, 102));
        btnUser_Delete.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnUser_Delete.setForeground(new java.awt.Color(255, 255, 255));
        btnUser_Delete.setText("Delete");
        btnUser_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUser_DeleteActionPerformed(evt);
            }
        });

        btnUser_back.setBackground(new java.awt.Color(102, 102, 102));
        btnUser_back.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnUser_back.setForeground(new java.awt.Color(255, 255, 255));
        btnUser_back.setText("← Back");
        btnUser_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUser_backActionPerformed(evt);
            }
        });

        eval_procedure.setBackground(new java.awt.Color(102, 102, 102));
        eval_procedure.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        eval_procedure.setForeground(new java.awt.Color(255, 255, 255));
        eval_procedure.setText("searchByEvaluator");
        eval_procedure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eval_procedureActionPerformed(evt);
            }
        });

        graderange_procedure.setBackground(new java.awt.Color(102, 102, 102));
        graderange_procedure.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        graderange_procedure.setForeground(new java.awt.Color(255, 255, 255));
        graderange_procedure.setText("searchByGradeRange");
        graderange_procedure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graderange_procedureActionPerformed(evt);
            }
        });

        combo_eval.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        combo_eval.setSelectedIndex(-1);

        gradestart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        gradeend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel1.setText("--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnUser_Delete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUser_back))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(graderange_procedure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eval_procedure, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gradestart, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(3, 3, 3)
                                .addComponent(gradeend, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(combo_eval, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUser_Delete)
                    .addComponent(btnUser_back))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eval_procedure)
                    .addComponent(combo_eval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(graderange_procedure)
                    .addComponent(gradestart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HApplies_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HApplies_TableMouseClicked
        

        DefaultTableModel RecordTable = (DefaultTableModel)HApplies_Table.getModel();
        int SelectedRows = HApplies_Table.getSelectedRow();

        
        

    }//GEN-LAST:event_HApplies_TableMouseClicked

    private void btnUser_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUser_DeleteActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)HApplies_Table.getModel();
        int SelectedRows = HApplies_Table.getSelectedRow();

        try{

            

            deleteItem = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this entry ?","Warning!",JOptionPane.YES_NO_OPTION);
            if (deleteItem == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.jdbc.Driver");
               Connection con = DriverManager.getConnection(DB_URL,username,password);
                PreparedStatement stmnt = con.prepareStatement("DELETE FROM history_applies WHERE employee = ? and job = ? and evaluator1 = ? and evaluator2 = ? and status = ? and average = ?");

                stmnt.setString(1,RecordTable.getValueAt(SelectedRows, 0).toString());
                stmnt.setString(2,RecordTable.getValueAt(SelectedRows, 1).toString());
                stmnt.setString(3, RecordTable.getValueAt(SelectedRows, 2).toString());
                stmnt.setString(4, RecordTable.getValueAt(SelectedRows, 3).toString());
                stmnt.setString(5, RecordTable.getValueAt(SelectedRows, 4).toString());
                stmnt.setString(6, RecordTable.getValueAt(SelectedRows, 5).toString());
                stmnt.executeUpdate();
                JOptionPane.showMessageDialog(this,"Entry Deleted");
                UpdateDB();

                
            }
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Applies_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLException ex){
            System.err.println(ex);
        } 
    }//GEN-LAST:event_btnUser_DeleteActionPerformed

    private void btnUser_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUser_backActionPerformed
        this.setVisible(false);
        new Table_Select().toFront();
        new Table_Select().setVisible(true);
        new Table_Select().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_btnUser_backActionPerformed

    private void eval_procedureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eval_procedureActionPerformed
        eval_Dialog.setVisible(true);
        eval_name.setText((String) combo_eval.getSelectedItem());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);

            PreparedStatement stmnt = con.prepareStatement("call SearchByEvaluator(?)");

            stmnt.setString(1, (String) combo_eval.getSelectedItem());
            ResultSet resultSet = stmnt.executeQuery();
            ResultSetMetaData metadata = resultSet.getMetaData();
            int numberOfColumns = metadata.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)eval_table.getModel();
                    RecordTable.setRowCount(0);
                    
             while (resultSet.next()){
                 
             Vector columnData = new Vector();
                for (int i = 1; i <= numberOfColumns; i++){
                    columnData.add(resultSet.getString("employee"));
                    columnData.add(resultSet.getString("job"));                    
                    
                    
                  
                }                 
                RecordTable.addRow(columnData);
             }
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Evaluator_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(Evaluator_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }
                                                       
    }//GEN-LAST:event_eval_procedureActionPerformed

    private void graderange_procedureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graderange_procedureActionPerformed
        grade_dialog.setVisible(true);
        startgrade_txt.setText((String) gradestart.getSelectedItem());
        endgrade_txt.setText((String) gradeend.getSelectedItem());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);

            PreparedStatement stmnt = con.prepareStatement("call SearchByGradeRange(?,?)");

            stmnt.setString(1, (String) gradestart.getSelectedItem());
            stmnt.setString(2, (String) gradeend.getSelectedItem());
            ResultSet resultSet = stmnt.executeQuery();
            ResultSetMetaData metadata = resultSet.getMetaData();
            int numberOfColumns = metadata.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)grade_table.getModel();
                    RecordTable.setRowCount(0);
                    
             while (resultSet.next()){
                 
             Vector columnData = new Vector();
                for (int i = 1; i <= numberOfColumns; i++){
                    columnData.add(resultSet.getString("employee"));
                    columnData.add(resultSet.getString("job"));                    
                    
                    
                  
                }                 
                RecordTable.addRow(columnData);
             }
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Evaluator_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(Evaluator_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }
                                                    
    }//GEN-LAST:event_graderange_procedureActionPerformed

    private void eval_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eval_tableMouseClicked
        
    }//GEN-LAST:event_eval_tableMouseClicked

    private void DialogBack_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DialogBack_btnActionPerformed
        eval_Dialog.setVisible(false);
  
    }//GEN-LAST:event_DialogBack_btnActionPerformed

    private void DialogBack_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DialogBack_btn2ActionPerformed
        grade_dialog.setVisible(false);
    }//GEN-LAST:event_DialogBack_btn2ActionPerformed

    private void grade_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grade_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_grade_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryApplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryApplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryApplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryApplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryApplies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DialogBack_btn;
    private javax.swing.JButton DialogBack_btn2;
    private javax.swing.JTable HApplies_Table;
    private javax.swing.JButton btnUser_Delete;
    private javax.swing.JButton btnUser_back;
    private javax.swing.JComboBox<String> combo_eval;
    private javax.swing.JLabel endgrade_txt;
    private javax.swing.JDialog eval_Dialog;
    private javax.swing.JLabel eval_name;
    private javax.swing.JButton eval_procedure;
    private javax.swing.JTable eval_table;
    private javax.swing.JDialog grade_dialog;
    private javax.swing.JTable grade_table;
    private javax.swing.JComboBox<String> gradeend;
    private javax.swing.JButton graderange_procedure;
    private javax.swing.JComboBox<String> gradestart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel startgrade_txt;
    // End of variables declaration//GEN-END:variables
}
