
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Job_Edit extends javax.swing.JFrame {
    String DB_URL = SQL_GUI.DB_URL ;
    String username = SQL_GUI.USERNAME;
    String password = SQL_GUI.PASSWORD;
    private int deleteItem;
    
    /**
     * Creates new form Job_Edit
     */
    public Job_Edit() {
        initComponents();
        UpdateDB();
        UpdateCombo();
        dropdJob_evaluator.setSelectedItem(null);
        setLocationRelativeTo(null);
    }

    
    public  void UpdateDB() {
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            
            PreparedStatement stmnt = con.prepareStatement("SELECT * FROM job");
            
            ResultSet resultSet = stmnt.executeQuery();
            
            ResultSetMetaData metadata = resultSet.getMetaData();
            int numberOfColumns = metadata.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)Job_Table.getModel();
                    RecordTable.setRowCount(0);
                    
             while (resultSet.next()){
                 
             Vector columnData = new Vector();
                for (int i = 1; i <= numberOfColumns; i++){
                    columnData.add(resultSet.getString("id"));
                    columnData.add(resultSet.getDate("start_date"));
                    columnData.add(resultSet.getString("position"));
                    columnData.add(resultSet.getInt("salary"));
                    columnData.add(resultSet.getString("edra"));
                    columnData.add(resultSet.getString("evaluator"));
                    columnData.add(resultSet.getDate("announce_date"));
                    columnData.add(resultSet.getDate("submission_date"));
                    
                }                 
                RecordTable.addRow(columnData);
             }
       
        }catch (Exception ex) {
             JOptionPane.showMessageDialog(null, ex);
        }
     } 
    
    public void UpdateCombo(){
        String dropdown = "Select * from evaluator";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            PreparedStatement stmnt = con.prepareStatement(dropdown);
            ResultSet rs = stmnt.executeQuery();
            
            while(rs.next()){
                dropdJob_evaluator.addItem(rs.getString("username"));
            }
            
        }catch (Exception e){
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtJob_ID = new javax.swing.JTextField();
        txtJob_salary = new javax.swing.JTextField();
        txtJob_position = new javax.swing.JTextField();
        txtJob_edra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Job_Table = new javax.swing.JTable();
        btnEtaireia_Delete = new javax.swing.JButton();
        btnEtaireia_back = new javax.swing.JButton();
        btnEtaireia_Update = new javax.swing.JButton();
        btnEtaireia_Insert = new javax.swing.JButton();
        btnEtaireia_Reset = new javax.swing.JButton();
        dropdJob_evaluator = new javax.swing.JComboBox<>();
        txtJob_startdate = new com.toedter.calendar.JDateChooser();
        txtJob_announcedate = new com.toedter.calendar.JDateChooser();
        txtJob_subdate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("ID :");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Start Date :");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Salary :");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Position :");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Edra :");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Evaluator :");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Announce Date:");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Submission Date :");

        txtJob_ID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtJob_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJob_IDActionPerformed(evt);
            }
        });

        txtJob_salary.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtJob_position.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtJob_edra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Job");

        Job_Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Job_Table.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        Job_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Start Date", "Position", "Salary", "Edra", "Evaluator", "Announce Date", "Submission Date"
            }
        ));
        Job_Table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Job_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Job_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Job_Table);

        btnEtaireia_Delete.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_Delete.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_Delete.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_Delete.setText("Delete");
        btnEtaireia_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_DeleteActionPerformed(evt);
            }
        });

        btnEtaireia_back.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_back.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_back.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_back.setText("← Back");
        btnEtaireia_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_backActionPerformed(evt);
            }
        });

        btnEtaireia_Update.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_Update.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_Update.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_Update.setText("Update");
        btnEtaireia_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_UpdateActionPerformed(evt);
            }
        });

        btnEtaireia_Insert.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_Insert.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_Insert.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_Insert.setText("Insert");
        btnEtaireia_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_InsertActionPerformed(evt);
            }
        });

        btnEtaireia_Reset.setBackground(new java.awt.Color(102, 102, 102));
        btnEtaireia_Reset.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnEtaireia_Reset.setForeground(new java.awt.Color(255, 255, 255));
        btnEtaireia_Reset.setText("Reset");
        btnEtaireia_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtaireia_ResetActionPerformed(evt);
            }
        });

        txtJob_startdate.setDateFormatString("yyyy-MM-dd");

        txtJob_announcedate.setDateFormatString("yyyy-MM-dd");
        txtJob_announcedate.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtJob_announcedateComponentAdded(evt);
            }
        });

        txtJob_subdate.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(btnEtaireia_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(571, 571, 571))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnEtaireia_Insert)
                                .addGap(8, 8, 8)
                                .addComponent(btnEtaireia_Update)
                                .addGap(5, 5, 5)
                                .addComponent(btnEtaireia_Delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEtaireia_back))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtJob_subdate, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(dropdJob_evaluator, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtJob_edra)
                                    .addComponent(txtJob_position)
                                    .addComponent(txtJob_salary)
                                    .addComponent(txtJob_ID)
                                    .addComponent(txtJob_startdate, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(txtJob_announcedate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel2)
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtJob_edra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(dropdJob_evaluator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJob_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addComponent(txtJob_startdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJob_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJob_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtJob_announcedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtJob_subdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEtaireia_Reset)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEtaireia_Insert)
                    .addComponent(btnEtaireia_Update)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEtaireia_Delete)
                        .addComponent(btnEtaireia_back)))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJob_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJob_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJob_IDActionPerformed

    private void Job_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Job_TableMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)Job_Table.getModel();
        int SelectedRows = Job_Table.getSelectedRow();
                
        txtJob_ID.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        try{
        Date start_date  = new SimpleDateFormat("yyyy-MM-dd").parse(RecordTable.getValueAt(SelectedRows, 1).toString());
        txtJob_startdate.setDate(start_date);  
        }catch(Exception e){
            JOptionPane.showInternalMessageDialog(null,e);
        }
        txtJob_salary.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        txtJob_position.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        txtJob_edra.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        dropdJob_evaluator.setSelectedItem(RecordTable.getValueAt(SelectedRows, 5).toString());
        try{
            Date announce_date  = new SimpleDateFormat("yyyy-MM-dd").parse(RecordTable.getValueAt(SelectedRows, 6).toString());
            Date sub_date  = new SimpleDateFormat("yyyy-MM-dd").parse(RecordTable.getValueAt(SelectedRows, 7).toString());
        txtJob_announcedate.setDate(announce_date);
        txtJob_subdate.setDate(sub_date);
        }catch (Exception e){
            JOptionPane.showInternalMessageDialog(null,e);
        }
        
        txtJob_ID.disable();
    }//GEN-LAST:event_Job_TableMouseClicked

    private void btnEtaireia_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_DeleteActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)Job_Table.getModel();
        int SelectedRows = Job_Table.getSelectedRow();

        try{

            int id;
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());

            deleteItem = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this entry ?","Warning!",JOptionPane.YES_NO_OPTION);
            if (deleteItem == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection(DB_URL,username,password);
                PreparedStatement stmnt = con.prepareStatement("DELETE FROM job WHERE id = ?");

                stmnt.setLong(1, id);
                stmnt.executeUpdate();
                JOptionPane.showMessageDialog(this,"Entry Deleted");
                UpdateDB();

                txtJob_ID.setText("");
                txtJob_ID.requestFocus();
                txtJob_startdate.setDate(null);
                txtJob_salary.setText("");
                txtJob_position.setText("");
                txtJob_edra.setText("");
                dropdJob_evaluator.setSelectedItem(null);
                txtJob_announcedate.setDate(null);
                txtJob_subdate.setDate(null);
            }
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Job_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLException ex){
            System.err.println(ex);
        }
    }//GEN-LAST:event_btnEtaireia_DeleteActionPerformed

    private void btnEtaireia_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_backActionPerformed
        this.setVisible(false);
        new Table_Select().toFront();
        new Table_Select().setVisible(true);
        new Table_Select().setState(java.awt.Frame.NORMAL);

    }//GEN-LAST:event_btnEtaireia_backActionPerformed

    private void btnEtaireia_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_UpdateActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String start_date = sdf.format(txtJob_startdate.getDate());
            String announce_date = sdf.format(txtJob_announcedate.getDate());
            String sub_date = sdf.format(txtJob_subdate.getDate());
            PreparedStatement stmnt = con.prepareStatement("UPDATE job SET  start_date = ?, position = ?, salary = ?, edra = ?,evaluator = ?,announce_date = ?,submission_date = ? WHERE id = ?");

            stmnt.setString(1,start_date);
            stmnt.setString(2,txtJob_salary.getText());
            stmnt.setString(3,txtJob_position.getText());
            stmnt.setString(4,txtJob_edra.getText());
            stmnt.setString(5,dropdJob_evaluator.getItemAt(0));
            stmnt.setString(6,announce_date);
            stmnt.setString(7,sub_date);
            stmnt.setString(8,txtJob_ID.getText());

            stmnt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Record Updated");
            UpdateDB();
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Job_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(Job_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }
    }//GEN-LAST:event_btnEtaireia_UpdateActionPerformed

    private void btnEtaireia_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_InsertActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String start_date = sdf.format(txtJob_startdate.getDate());
            String announce_date = sdf.format(txtJob_announcedate.getDate());
            String sub_date = sdf.format(txtJob_subdate.getDate());
            
            PreparedStatement stmnt = con.prepareStatement("INSERT INTO job(id,start_date,position,salary,edra,evaluator,announce_date,submission_date)value(?,?,?,?,?,?,?,?)");

            stmnt.setString(1,txtJob_ID.getText());
            stmnt.setString(2,start_date);
            stmnt.setString(3,txtJob_salary.getText());
            stmnt.setString(4,txtJob_position.getText());
            stmnt.setString(5,txtJob_edra.getText());
            stmnt.setString(6,dropdJob_evaluator.getItemAt(0));
            stmnt.setString(7,announce_date);
            stmnt.setString(8,sub_date);

            stmnt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            UpdateDB();
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Etaireia_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(null,"Job entry already exists");
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(Etaireia_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }
    }//GEN-LAST:event_btnEtaireia_InsertActionPerformed

    private void btnEtaireia_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtaireia_ResetActionPerformed
        txtJob_ID.setText("");
        txtJob_startdate.setDate(null);
        txtJob_salary.setText("");
        txtJob_position.setText("");
        txtJob_edra.setText("");
        dropdJob_evaluator.setSelectedItem(null);
        txtJob_announcedate.setDate(null);
        txtJob_subdate.setDate(null);
        
        txtJob_ID.enable();
    }//GEN-LAST:event_btnEtaireia_ResetActionPerformed

    private void txtJob_announcedateComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtJob_announcedateComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJob_announcedateComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Job_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Job_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Job_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Job_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Job_Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Job_Table;
    private javax.swing.JButton btnEtaireia_Delete;
    private javax.swing.JButton btnEtaireia_Insert;
    private javax.swing.JButton btnEtaireia_Reset;
    private javax.swing.JButton btnEtaireia_Update;
    private javax.swing.JButton btnEtaireia_back;
    private javax.swing.JComboBox<String> dropdJob_evaluator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtJob_ID;
    private com.toedter.calendar.JDateChooser txtJob_announcedate;
    private javax.swing.JTextField txtJob_edra;
    private javax.swing.JTextField txtJob_position;
    private javax.swing.JTextField txtJob_salary;
    private com.toedter.calendar.JDateChooser txtJob_startdate;
    private com.toedter.calendar.JDateChooser txtJob_subdate;
    // End of variables declaration//GEN-END:variables
}
