
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Lang_Edit extends javax.swing.JFrame {
   String DB_URL = SQL_GUI.DB_URL ;
   String username = SQL_GUI.USERNAME;
   String password = SQL_GUI.PASSWORD;
    private int deleteItem;
    public String existingtext;
    
    /**
     * Creates new form Lang_Edit
     */
    public Lang_Edit() {
        initComponents();
        UpdateDB();
        UpdateCombo_employee();
        setLocationRelativeTo(null);
    }
    
    public  void UpdateDB() {
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            
            PreparedStatement stmnt = con.prepareStatement("SELECT * FROM languages");
            
            ResultSet resultSet = stmnt.executeQuery();
            
            ResultSetMetaData metadata = resultSet.getMetaData();
            int numberOfColumns = metadata.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)Lang_Table.getModel();
                    RecordTable.setRowCount(0);
                    
             while (resultSet.next()){
                 
             Vector columnData = new Vector();
                for (int i = 1; i <= numberOfColumns; i++){
                    columnData.add(resultSet.getString("candid"));
                    columnData.add(resultSet.getString("lang"));
                    
                    
                    
                }                 
                RecordTable.addRow(columnData);
             }
       
        }catch (Exception ex) {
             JOptionPane.showMessageDialog(null, ex);
        }
     } 
    public void UpdateCombo_employee(){
        String dropdown = "Select * from employee";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            PreparedStatement stmnt = con.prepareStatement(dropdown);
            ResultSet rs = stmnt.executeQuery();
            
            while(rs.next()){
                txtLang_employee.addItem(rs.getString("username"));
            }
            
        }catch (Exception e){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        btn_Insert = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lang_Table = new javax.swing.JTable();
        btn_Delete = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtLang_lang = new javax.swing.JTextField();
        txtLang_employee = new javax.swing.JComboBox<>();
        btn_en = new javax.swing.JRadioButton();
        btn_gr = new javax.swing.JRadioButton();
        btn_ch = new javax.swing.JRadioButton();
        btn_ge = new javax.swing.JRadioButton();
        btn_sp = new javax.swing.JRadioButton();
        btn_fr = new javax.swing.JRadioButton();
        refresh = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Insert.setBackground(new java.awt.Color(102, 102, 102));
        btn_Insert.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_Insert.setForeground(new java.awt.Color(255, 255, 255));
        btn_Insert.setText("Insert");
        btn_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertActionPerformed(evt);
            }
        });

        btn_Reset.setBackground(new java.awt.Color(102, 102, 102));
        btn_Reset.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_Reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_Reset.setText("Reset");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        btn_Update.setBackground(new java.awt.Color(102, 102, 102));
        btn_Update.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_Update.setForeground(new java.awt.Color(255, 255, 255));
        btn_Update.setText("Update");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Languages");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Languages :");

        Lang_Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Lang_Table.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        Lang_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee", "Languages"
            }
        ));
        Lang_Table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Lang_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lang_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Lang_Table);

        btn_Delete.setBackground(new java.awt.Color(102, 102, 102));
        btn_Delete.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_Delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_Delete.setText("Delete");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(102, 102, 102));
        btn_back.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("← Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Employee :");

        txtLang_lang.setEnabled(false);
        txtLang_lang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLang_langActionPerformed(evt);
            }
        });

        txtLang_employee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        txtLang_employee.setSelectedIndex(-1);

        btn_en.setText("English");
        btn_en.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enActionPerformed(evt);
            }
        });

        btn_gr.setText("Greek");
        btn_gr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grActionPerformed(evt);
            }
        });

        btn_ch.setText("Chinese");
        btn_ch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chActionPerformed(evt);
            }
        });

        btn_ge.setText("German");
        btn_ge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geActionPerformed(evt);
            }
        });

        btn_sp.setText("Spanish");
        btn_sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_spActionPerformed(evt);
            }
        });

        btn_fr.setText("French");
        btn_fr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frActionPerformed(evt);
            }
        });

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Insert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Delete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_back)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(refresh)
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtLang_lang)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_en)
                                .addGap(37, 37, 37)
                                .addComponent(btn_ge))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_fr)
                                    .addComponent(btn_sp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_gr)
                                    .addComponent(btn_ch)))
                            .addComponent(txtLang_employee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtLang_employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLang_lang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_en)
                            .addComponent(btn_ge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_fr)
                            .addComponent(btn_ch)
                            .addComponent(refresh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_sp)
                            .addComponent(btn_gr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_Reset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_Delete)
                                    .addComponent(btn_Update)
                                    .addComponent(btn_Insert)))
                            .addComponent(btn_back, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);

            PreparedStatement stmnt = con.prepareStatement("INSERT INTO languages(candid,lang) values (?,?)");

            stmnt.setString(1, (String) txtLang_employee.getSelectedItem());
            stmnt.setString(2,txtLang_lang.getText());

            stmnt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            UpdateDB();
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Lang_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(null,"Language entry already exists");
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(Lang_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }
    }//GEN-LAST:event_btn_InsertActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed

        txtLang_employee.setSelectedItem(null);
        txtLang_lang.setText(null);
        btn_en.setSelected(false);
                btn_fr.setSelected(false);
                btn_sp.setSelected(false);
                btn_ge.setSelected(false);
                btn_ch.setSelected(false);
                btn_gr.setSelected(false);
        
        txtLang_employee.enable();
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);

            PreparedStatement stmnt = con.prepareStatement("UPDATE languages SET lang = ? where candid = ? ");

            stmnt.setString(1,txtLang_lang.getText());
            stmnt.setString(2, (String) txtLang_employee.getSelectedItem());
            

            stmnt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Record Updated");
            UpdateDB();
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Lang_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(Lang_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        } 
    }//GEN-LAST:event_btn_UpdateActionPerformed
 
    private void Lang_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lang_TableMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)Lang_Table.getModel();
        int SelectedRows = Lang_Table.getSelectedRow();

        txtLang_employee.setSelectedItem(RecordTable.getValueAt(SelectedRows, 0).toString());
        txtLang_lang.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        
        txtLang_employee.disable();
        existingtext = txtLang_lang.getText();
        
        
         if (existingtext.contains("EN")){
            btn_en.setSelected(true);
            
            
        }
         else {
             btn_en.setSelected(false);
             
         }
         
         
         if (existingtext.contains("FR")){
            btn_fr.setSelected(true);
            
        }
         else {
             btn_fr.setSelected(false);
         }
         
         
         if (existingtext.contains("SP")){
            btn_sp.setSelected(true);
            
        }
         else {
             btn_sp.setSelected(false);
         }
         
         
         if (existingtext.contains("GE")){
            btn_ge.setSelected(true);
            
        }
         else {
             btn_ge.setSelected(false);
         }
         
         
         if (existingtext.contains("CH")){
            btn_ch.setSelected(true);
            
        }
         else {
             btn_ch.setSelected(false);
         }
         
         
         if (existingtext.contains("GR")){
            btn_gr.setSelected(true);
            
        }
         else {
             btn_gr.setSelected(false);
         }
        
    }//GEN-LAST:event_Lang_TableMouseClicked

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)Lang_Table.getModel();
        int SelectedRows = Lang_Table.getSelectedRow();

        try{

            String usernm;
            usernm = (RecordTable.getValueAt(SelectedRows, 0).toString());

            deleteItem = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this entry ?","Warning!",JOptionPane.YES_NO_OPTION);
            if (deleteItem == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection(DB_URL,username,password);
                PreparedStatement stmnt = con.prepareStatement("DELETE FROM languages WHERE candid = ?");

                stmnt.setString(1, usernm);
                stmnt.executeUpdate();
                JOptionPane.showMessageDialog(this,"Entry Deleted");
                UpdateDB();

                txtLang_employee.setSelectedItem(null);
                txtLang_lang.setText(null);
                btn_en.setSelected(false);
                btn_fr.setSelected(false);
                btn_sp.setSelected(false);
                btn_ge.setSelected(false);
                btn_ch.setSelected(false);
                btn_gr.setSelected(false);


            }
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Subject_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLException ex){
            System.err.println(ex);
        }
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.setVisible(false);
        new Table_Select().toFront();
        new Table_Select().setVisible(true);
        new Table_Select().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_btn_backActionPerformed

    private void txtLang_langActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLang_langActionPerformed
        
    }//GEN-LAST:event_txtLang_langActionPerformed

    private void btn_enActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enActionPerformed
       
    }//GEN-LAST:event_btn_enActionPerformed

    private void btn_grActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grActionPerformed
              
    }//GEN-LAST:event_btn_grActionPerformed

    private void btn_chActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chActionPerformed

    }//GEN-LAST:event_btn_chActionPerformed

    private void btn_geActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geActionPerformed
      
    }//GEN-LAST:event_btn_geActionPerformed

    private void btn_spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_spActionPerformed
    
    }//GEN-LAST:event_btn_spActionPerformed

    private void btn_frActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frActionPerformed
      
    }//GEN-LAST:event_btn_frActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        existingtext = "";
        if (btn_en.isSelected()){
            if (existingtext == ""){
                existingtext = "EN";
            }
            else {
                existingtext = existingtext + ",EN";
            }
        }
        if (btn_fr.isSelected()){
            if (existingtext == ""){
                existingtext = "FR";
            }
            else {
                existingtext = existingtext + ",FR";
            }
        }
        if (btn_sp.isSelected()){
            if (existingtext == ""){
                existingtext = "SP";
            }
            else {
                existingtext = existingtext + ",SP";
            }
        }
        if (btn_ge.isSelected()){
            if (existingtext == ""){
                existingtext = "GE";
            }
            else {
                existingtext = existingtext + ",GE";
            }
        }
        if (btn_ch.isSelected()){
            if (existingtext == ""){
                existingtext = "CH";
            }
            else {
                existingtext = existingtext + ",CH";
            }
        }
        if (btn_gr.isSelected()){
            if (existingtext == ""){
                existingtext = "GR";
            }
            else {
                existingtext = existingtext + ",GR";
            }
        }
        txtLang_lang.setText(existingtext);
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lang_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lang_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lang_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lang_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lang_Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Lang_Table;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Insert;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_back;
    public javax.swing.JRadioButton btn_ch;
    public javax.swing.JRadioButton btn_en;
    public javax.swing.JRadioButton btn_fr;
    public javax.swing.JRadioButton btn_ge;
    public javax.swing.JRadioButton btn_gr;
    public javax.swing.JRadioButton btn_sp;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh;
    private javax.swing.JComboBox<String> txtLang_employee;
    private javax.swing.JTextField txtLang_lang;
    // End of variables declaration//GEN-END:variables
}
