
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Table_Select extends javax.swing.JFrame {
 
    /**
     * Creates new form Table_Select
     */
    public Table_Select() {        
        initComponents(); 
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dropdown_menu = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        log_btn = new javax.swing.JButton();
        select_btn = new javax.swing.JButton();
        dba_edit_btn = new javax.swing.JButton();

        jButton3.setText("Log");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Select which table to edit:");

        dropdown_menu.setEditable(true);
        dropdown_menu.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        dropdown_menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Etaireia", "User", "Evaluator", "Employee", "Job", "Subject", "Requires", "Languages", "Project", "Applies", "Degree", "Has_degree", "Job_Employee", "History_Applies", " " }));
        dropdown_menu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dropdown_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_menuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Table name:");

        back_btn.setBackground(new java.awt.Color(102, 102, 102));
        back_btn.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("← Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        log_btn.setBackground(new java.awt.Color(102, 102, 102));
        log_btn.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        log_btn.setForeground(new java.awt.Color(255, 255, 255));
        log_btn.setText("Log");
        log_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_btnActionPerformed(evt);
            }
        });

        select_btn.setBackground(new java.awt.Color(102, 102, 102));
        select_btn.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        select_btn.setForeground(new java.awt.Color(255, 255, 255));
        select_btn.setText("Select");
        select_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_btnActionPerformed(evt);
            }
        });

        dba_edit_btn.setBackground(new java.awt.Color(102, 102, 102));
        dba_edit_btn.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        dba_edit_btn.setForeground(new java.awt.Color(255, 255, 255));
        dba_edit_btn.setText("Data Base Admins");
        dba_edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dba_edit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(log_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dba_edit_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(select_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dropdown_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1)))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdown_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(log_btn)
                    .addComponent(back_btn)
                    .addComponent(dba_edit_btn))
                .addContainerGap())
        );

        dropdown_menu.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropdown_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_menuActionPerformed
        
    
    }//GEN-LAST:event_dropdown_menuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void select_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_btnActionPerformed
        this.setVisible(false);
        if ("Etaireia".equals((String)dropdown_menu.getSelectedItem())){            
            new Etaireia_Edit().setVisible(true);
        }   
        else if("User".equals((String)dropdown_menu.getSelectedItem())){
         new User_Edit().setVisible(true);
        }
        else if("Evaluator".equals((String)dropdown_menu.getSelectedItem())){
         new Evaluator_Edit().setVisible(true);
        }
        else if("Job".equals((String)dropdown_menu.getSelectedItem())){
         new Job_Edit().setVisible(true);
        }
        else if("Employee".equals((String)dropdown_menu.getSelectedItem())){
         new Employee_Edit().setVisible(true);
        }
        else if("Subject".equals((String)dropdown_menu.getSelectedItem())){
         new Subject_Edit().setVisible(true);
        }
        else if("Requires".equals((String)dropdown_menu.getSelectedItem())){
         new Requires_Edit().setVisible(true);
        }
        else if("Languages".equals((String)dropdown_menu.getSelectedItem())){
         new Lang_Edit().setVisible(true);
        }
        else if("Project".equals((String)dropdown_menu.getSelectedItem())){
         new Project_Edit().setVisible(true);
        }
        else if("Applies".equals((String)dropdown_menu.getSelectedItem())){
         new Applies_Edit().setVisible(true);
        }
        else if("Degree".equals((String)dropdown_menu.getSelectedItem())){
         new Degree_Edit().setVisible(true);
        }
        else if("Has_degree".equals((String)dropdown_menu.getSelectedItem())){
         new Has_Degree_Edit().setVisible(true);
        }
        else if("Job_Employee".equals((String)dropdown_menu.getSelectedItem())){
         new Job_Employee().setVisible(true);
        }
        else if("History_Applies".equals((String)dropdown_menu.getSelectedItem())){
         new HistoryApplies().setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_select_btnActionPerformed

    private void log_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_btnActionPerformed
        this.setVisible(false);
        new Log_Table().setVisible(true);
    }//GEN-LAST:event_log_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        this.setVisible(false);
        new DBA_Login().toFront();
        new DBA_Login().setVisible(true);
        new DBA_Login().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_back_btnActionPerformed

    private void dba_edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dba_edit_btnActionPerformed
       
        this.setVisible(false);
        new DBA_Edit().setVisible(true);
       
    }//GEN-LAST:event_dba_edit_btnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table_Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table_Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table_Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table_Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table_Select().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton dba_edit_btn;
    private javax.swing.JComboBox<String> dropdown_menu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton log_btn;
    private javax.swing.JButton select_btn;
    // End of variables declaration//GEN-END:variables
}
