
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class User_Edit extends javax.swing.JFrame {
    String DB_URL = SQL_GUI.DB_URL ;
   String username = SQL_GUI.USERNAME;
   String password = SQL_GUI.PASSWORD;
    private int deleteItem;
    /**
     * Creates new form User_Edit
     */
    public User_Edit() {
        initComponents();
        UpdateDB();
        setLocationRelativeTo(null);
    }
    
     public  void UpdateDB() {
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            
            PreparedStatement stmnt = con.prepareStatement("SELECT * FROM user");
            
            ResultSet resultSet = stmnt.executeQuery();
            
            ResultSetMetaData metadata = resultSet.getMetaData();
            int numberOfColumns = metadata.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)User_Table.getModel();
                    RecordTable.setRowCount(0);
                    
             while (resultSet.next()){
                 
             Vector columnData = new Vector();
                for (int i = 1; i <= numberOfColumns; i++){
                    columnData.add(resultSet.getString("Username"));
                    columnData.add(resultSet.getString("Password"));
                    columnData.add(resultSet.getString("Name"));
                    columnData.add(resultSet.getString("Lastname"));
                    columnData.add(resultSet.getString("reg_date"));
                    columnData.add(resultSet.getString("Email"));
                    
                }                 
                RecordTable.addRow(columnData);
             }
       
        }catch (Exception ex) {
             JOptionPane.showMessageDialog(null, ex);
        }
     } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUser_username = new javax.swing.JTextField();
        txtUser_password = new javax.swing.JTextField();
        txtUser_Name = new javax.swing.JTextField();
        txtUser_Lastname = new javax.swing.JTextField();
        txtUser_email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        User_Table = new javax.swing.JTable();
        btnUser_Delete = new javax.swing.JButton();
        btnUser_back = new javax.swing.JButton();
        btnUser_Update = new javax.swing.JButton();
        btnUser_Insert = new javax.swing.JButton();
        btnUser_Reset = new javax.swing.JButton();
        txtUser_reg_date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Username :");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Password :");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Name :");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Lastname :");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Registration Date :");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Email :");

        txtUser_username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtUser_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUser_usernameActionPerformed(evt);
            }
        });

        txtUser_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtUser_Name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtUser_Lastname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txtUser_email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("User");

        User_Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        User_Table.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        User_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Name", "Lastname", "Registration Date", "Email"
            }
        ));
        User_Table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        User_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                User_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(User_Table);

        btnUser_Delete.setBackground(new java.awt.Color(102, 102, 102));
        btnUser_Delete.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnUser_Delete.setForeground(new java.awt.Color(255, 255, 255));
        btnUser_Delete.setText("Delete");
        btnUser_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUser_DeleteActionPerformed(evt);
            }
        });

        btnUser_back.setBackground(new java.awt.Color(102, 102, 102));
        btnUser_back.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnUser_back.setForeground(new java.awt.Color(255, 255, 255));
        btnUser_back.setText("← Back");
        btnUser_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUser_backActionPerformed(evt);
            }
        });

        btnUser_Update.setBackground(new java.awt.Color(102, 102, 102));
        btnUser_Update.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnUser_Update.setForeground(new java.awt.Color(255, 255, 255));
        btnUser_Update.setText("Update");
        btnUser_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUser_UpdateActionPerformed(evt);
            }
        });

        btnUser_Insert.setBackground(new java.awt.Color(102, 102, 102));
        btnUser_Insert.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnUser_Insert.setForeground(new java.awt.Color(255, 255, 255));
        btnUser_Insert.setText("Insert");
        btnUser_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUser_InsertActionPerformed(evt);
            }
        });

        btnUser_Reset.setBackground(new java.awt.Color(102, 102, 102));
        btnUser_Reset.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnUser_Reset.setForeground(new java.awt.Color(255, 255, 255));
        btnUser_Reset.setText("Reset");
        btnUser_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUser_ResetActionPerformed(evt);
            }
        });

        txtUser_reg_date.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnUser_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUser_reg_date, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(txtUser_Lastname)
                                    .addComponent(txtUser_Name)
                                    .addComponent(txtUser_password)
                                    .addComponent(txtUser_username)
                                    .addComponent(txtUser_email))
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUser_Insert)
                                .addGap(6, 6, 6)
                                .addComponent(btnUser_Update)
                                .addGap(6, 6, 6)
                                .addComponent(btnUser_Delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUser_back)
                                .addGap(49, 49, 49)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUser_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUser_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUser_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUser_Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUser_reg_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtUser_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addComponent(btnUser_Reset)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUser_Insert)
                    .addComponent(btnUser_Update)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUser_Delete)
                        .addComponent(btnUser_back)))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUser_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUser_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser_usernameActionPerformed

    private void User_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_TableMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)User_Table.getModel();
        int SelectedRows = User_Table.getSelectedRow();

        txtUser_username.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        txtUser_password.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        txtUser_Name.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        txtUser_Lastname.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        try{
            Date reg_date = new SimpleDateFormat("yyyy-MM-dd").parse(RecordTable.getValueAt(SelectedRows, 4).toString());
        txtUser_reg_date.setDate(reg_date);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        txtUser_email.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        
        txtUser_username.disable();
    }//GEN-LAST:event_User_TableMouseClicked

    private void btnUser_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUser_DeleteActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)User_Table.getModel();
        int SelectedRows = User_Table.getSelectedRow();

        try{

            String usernm;
            usernm = (RecordTable.getValueAt(SelectedRows, 0).toString());

            deleteItem = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this entry ?","Warning!",JOptionPane.YES_NO_OPTION);
            if (deleteItem == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection(DB_URL,username,password);
                PreparedStatement stmnt = con.prepareStatement("DELETE FROM user WHERE username = ?");

                stmnt.setString(1, usernm);
                stmnt.executeUpdate();
                JOptionPane.showMessageDialog(this,"Entry Deleted");
                UpdateDB();

                txtUser_username.setText("");
                txtUser_username.requestFocus();
                txtUser_password.setText("");
                txtUser_Name.setText("");
                txtUser_Lastname.setText("");
                txtUser_reg_date.setDate(null);
                txtUser_email.setText("");
                
            }
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(Etaireia_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLException ex){
            System.err.println(ex);
        } 
    }//GEN-LAST:event_btnUser_DeleteActionPerformed

    private void btnUser_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUser_UpdateActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String reg_date = sdf.format(txtUser_reg_date.getDate());
            PreparedStatement stmnt = con.prepareStatement("UPDATE user SET password = ?, name = ?,lastname = ?,reg_date = ?,email = ? where username = ?");

            stmnt.setString(1,txtUser_password.getText());
            stmnt.setString(2,txtUser_Name.getText());
            stmnt.setString(3,txtUser_Lastname.getText());
            stmnt.setString(4,reg_date);
            stmnt.setString(5,txtUser_email.getText());
            stmnt.setString(6,txtUser_username.getText());

            stmnt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Record Updated");
            UpdateDB();
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(User_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(User_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }
    }//GEN-LAST:event_btnUser_UpdateActionPerformed

    private void btnUser_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUser_InsertActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(DB_URL,username,password);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String reg_date = sdf.format(txtUser_reg_date.getDate());
            PreparedStatement stmnt = con.prepareStatement("INSERT INTO user(username,password,name,lastname,reg_date,email)value(?,?,?,?,?,?)");

            stmnt.setString(1,txtUser_username.getText());
            stmnt.setString(2,txtUser_password.getText());
            stmnt.setString(3,txtUser_Name.getText());
            stmnt.setString(4,txtUser_Lastname.getText());
            stmnt.setString(5,reg_date);
            stmnt.setString(6,txtUser_email.getText());
           

            stmnt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            UpdateDB();
        }catch (ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(User_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }catch (SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(null,"User entry already exists");
        }catch (SQLException ex){
            java.util.logging.Logger.getLogger(User_Edit.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
        }
    }//GEN-LAST:event_btnUser_InsertActionPerformed

    private void btnUser_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUser_ResetActionPerformed
        txtUser_username.setText("");
        txtUser_password.setText("");
        txtUser_Name.setText("");
        txtUser_Lastname.setText("");
        txtUser_reg_date.setDate(null);
        txtUser_email.setText("");
        
         txtUser_username.enable();
    }//GEN-LAST:event_btnUser_ResetActionPerformed

    private void btnUser_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUser_backActionPerformed
        this.setVisible(false);
        new Table_Select().toFront();
         new Table_Select().setVisible(true);
        new Table_Select().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_btnUser_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable User_Table;
    private javax.swing.JButton btnUser_Delete;
    private javax.swing.JButton btnUser_Insert;
    private javax.swing.JButton btnUser_Reset;
    private javax.swing.JButton btnUser_Update;
    private javax.swing.JButton btnUser_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtUser_Lastname;
    private javax.swing.JTextField txtUser_Name;
    private javax.swing.JTextField txtUser_email;
    private javax.swing.JTextField txtUser_password;
    private com.toedter.calendar.JDateChooser txtUser_reg_date;
    private javax.swing.JTextField txtUser_username;
    // End of variables declaration//GEN-END:variables
}
